[project]
name = "horn-geometry"
version = "0.1.0"
description = "Procedural geometry generation for the Horn project."
dependencies = [
    "numpy",
    "gmsh"
]

[project.scripts]
horn-geometry = "horn_geometry.generator:main"

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.uv.sources]
horn-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 